### PR TITLE
Fix #421

### LINKED ISSUE #421: Dark Prince's Envoy/Daemon Whisperer (Cult of Pleasure Ancillaries) spread/trigger from chaos undivided corruption
Like everything Morathi related, makes sense that this should be Slaanesh corruption and not undivided

image

### PR DESCRIPTION
**Pull request by Gingerglaahk**
Fix #421 by changing both envoy and daemon whisperer to provide slaanesh corruption instead in undivided corruption

### CODE REVIEW

**Comment by mfvreeland** [comment]
There is no need to overwrite the whole followers script, and for the sake of future compatibility, I wouldn't recommend it. If it's just the one follower, the default listener that awards it can be removed and replaced by the altered listener in a new script.

**Review by mfvreeland — CHANGES_REQUESTED** [review]
Lua portion of this fix replaced with #487

**Review by mfvreeland — CHANGES_REQUESTED** [review]
Lua portion of this fix replaced with #487, please remove last two commits so we can merge the db changes

**Comment by Gingerglaahk** [comment]
@mfvreeland Done

**Review by mfvreeland — APPROVED** [review]
Thank you, @Gingerglaahk!

**Pull request merged**
