### PR TITLE
Various issues related to unit types for Tomb Kings (#1411 and #1403)

### PR DESCRIPTION
**Pull request by Grimmys**
- `inf_mis` unit category is now considered as a `missile_units` class in order to give missile related bonuses to every missile units.
- Casket of Souls unit caste is now warmachine instead of chariot, it's consistent with Screaming Skull Catapults caste.
- "Chariots Not On Fire" mission doesn't consider Casket of Souls as a valid chariot anymore, since it's now looking for units matching chariot caste instead of chariot class.
/!\ _Fix for "Chariots Not On Fire" works only on fresh instances of the mission, if the mission has been triggered before this fix, it's not going to work._

### CODE REVIEW

**Comment by Harmandodelavega** [comment]
I wouldn't touch unit castes and classes, maybe it's superstition but it could brick other things

**Comment by Grimmys** [comment]
I get your point, I'm also a bit afraid of consequences, but then what to do?

Regarding Casket of Souls, it seems pretty obvious to me that it's just having the wrong caste: it's not a chariot, but an artillery... On battle setup, it's listed in the same category as Skull Catapult, in battle, it's as fast as an artillery, not a chariot, and it has the range of an artillery.
So even if the change of caste breaks more things, in my opinion, it's these other things that should be fix.

If you really think it's an issue then I suggest this:
- I open a new PR containing only the first bullet point to fix Khalida's defeat trait. Casket of Souls would still not be targeted by the effect despite Skull Catapult being though.
- Close #1411 as "wont-fix".

**Comment by Harmandodelavega** [comment]
Unless I do some investigation or you can convince me it doesn't break anything let's leave the casket

**Comment by Grimmys** [comment]
Fair enough, they could be some side effects definitely.

My point was that "Infantry Missile" (`inf_mis`) should be by definition part of "Missile Units" (`missile_units`) class... Since well, it's about missiles.
There was also the that it's not going to be only Ushabti Great Bows units, but more (the serpents, Bone Giant etc.). And this is only about TK roster, but other rosters may also be impacted by this bug, and so doing a generic fix could have fix them as well.

Nevertheless, I'm going to open a new PR that will contain only the fix for Khalida's defeat trait, and strictly in the way you want it.

**Comment by mfvreeland** [comment]
@Grimmys I understand your point and agree with your logic, but CA isn't always super consistent with the way they use the class/caste designations, so my concern is making a change like this could have second order effects down the line that we would then have a hard time tracking back to a fix for Khalida's defeat trait. Really, I don't like messing with the caste stuff ever, although @Harmandodelavega may be right that it's at least partially modder superstition 😂

**Pull request closed without merging**
