### PR TITLE
Fix for issue #1390 , item and ancillary drop rate fix

### PR DESCRIPTION
**Pull request by floskan**

### CODE REVIEW

**Comment by mfvreeland** [comment]
This looks like a restoration of the old magic items script before it was changed in 4.1, which means it will introduce the old bugs as well. When I have time, I will look into fixing this the right way instead.

**Comment by floskan** [comment]
> This looks like a restoration of the old magic items script before it was changed in 4.1, which means it will introduce the old bugs as well. When I have time, I will look into fixing this the right way instead.

Good eye! Just using Drazhirs fix in the meantime then.

**Comment by mfvreeland** [comment]
@floskan Yes, that fix should work best for now. I will look into this script today and see if I can take what CA did in 4.1 and just fix that, will update here when finished.

**Comment by mfvreeland** [comment]
I can't reproduce the issue this bug is supposed to fix. Multiple ancillaries of the same type/rarity (or even the same exact ancillary) drop just fine for me.

**Comment by mfvreeland** [comment]
I was able to reproduce it and found the (very sneaky) culprit. The current fix on this PR preserves CA's dynamic table changes introduced in 4.1, which means the script doesn't need to be updated whenever ancillaries are added to the game.

**Pull request merged**
