### PR TITLE
Fix for issue #315 , Skaven tech and text fixes (Moulder units)

### PR DESCRIPTION
**Pull request by floskan**
Added back the two missing tech nodes that buffed brood horrors and wolf rats. Added back mutant rat ogres to tech and buildings (moulder special landmark) they also used to benefit from and made a new unit set with only them in it so they don't get double benefits from other buffs, also changed the loc to reflect that mutant rat ogres benefit from it.

### CODE REVIEW

**Comment by Harmandodelavega** [comment]
Couple nitpicks + a suggestion

1:Mutant rat ogre/s is both singular and plural in your loc
2:Your tables have different names, but for ease of navigation maybe you could give them the same name for similar issues, like"mutantrat ogre sets" and "skaventechs"

and finally there are more units missing from the tech tree, apparently going back as far as the Skryre dlc, maybe you could take a look?

**Comment by floskan** [comment]
> Couple nitpicks + a suggestion
> 
> 1:Mutant rat ogre/s is both singular and plural in your loc 2:Your tables have different names, but for ease of navigation maybe you could give them the same name for similar issues, like"mutantrat ogre sets" and "skaventechs"
> 
> and finally apparently there are more units/techs missing from the tech tree, going back to the Skryre dlc, maybe you could take a look?
> 
> "Tech practiced goaders either doesn't have any effect or is missing the tooltip" think it may be a Skryre exclusive tech, anyways near the skaven weapons team section

1. Yes you're right, i just typed it in as it appeared in wh2 without making it consistent, can take another look.
2. Thanks, will try to do so in the future.

I'm in the process of looking through the tech as i noticed that several eshin units were either not in the tech tree at all or just missing from the loc. The weapon teams buffs for example seems to hit all units but isn't mentioning all of them. I wonder if i should just change the loc to "skaven weapon teams" as it is in game 2 instead of the tooltip taking up half the screen.

**Comment by floskan** [comment]
Hm, practiced goaders seems to work. Is it only when you don't own the dlc it's weird? And i couldn't really find any errors with tech besides the loc not being updated.

**Comment by Rideorpi** [comment]
When are these fixes going to be added?

**Pull request merged**
