### PR TITLE
Fix for issue #1651 , Ascension trait for nurgle lord

### PR DESCRIPTION
**Pull request by floskan**

### CODE REVIEW

**Comment by floskan** [comment]
Would this work? I basically just copied one of your other fixes.

**Comment by mfvreeland** [comment]
I don't think it's possible for an Undivided Chaos Lord to morph straight into a Daemon Prince of Nurgle, is it?

**Comment by floskan** [comment]
It is if you're playing festus, I just copied your script from when you fixed the tzeentch lords not getting traits

**Review by mfvreeland — APPROVED** [review]
This should work!

**Comment by floskan** [comment]
This works!

**Pull request merged**
