### PR TITLE
Fix for tons of issues

### PR DESCRIPTION
**Pull request by floskan**
#161 #177 #184 #188 #193 #210 #270 #416 #519 #655 #659 #660 #671 #672 #673 #674 #675 #676 #677 #678 #679 #680 #682 #684 #685 #692 #744 #745 #753 #754 #774 #780 #784 #792 #794 #795 #796 #804

Fixes courtesy of @Harmandodelavega , for information for what fixes is in this, check the issues that's linked to this commit.

### CODE REVIEW

**Comment by Harmandodelavega** [comment]
Just fyi @floskan https://github.com/chadvandy/cbfm_wh3/issues/600 the Human Endal thing I meant that Endal was the right one

**Comment by floskan** [comment]
> Just fyi @floskan #600 the Human Endal thing I meant that Endal was the right one

@Harmandodelavega yeah i didn't include that change so it will stay Endal

**Comment by Harmandodelavega** [comment]
@floskan 
It's the other way around

**Comment by floskan** [comment]
> @floskan It's human on live and Endal in the fix

@Harmandodelavega ok, I'll just make a new PR for that later then

**Comment by Harmandodelavega** [comment]
I'll just manually edit I think

**Pull request merged**
