### PR TITLE
Fix #347 - Slaanesh corruption for Morathi Techs

### LINKED ISSUE #347: Morathi Techs Should Spread Slaanesh and not Undivided Corruption
image
image

### PR DESCRIPTION
**Pull request by Gingerglaahk**
Fix #347 by changing from chaos corruption (undivided) to slaanesh corruption

### CODE REVIEW

**Comment by floskan** [comment]
This doesn't remove the undivided corruption, you should add  

wh2_main_tech_def_1_3_3_slaanesh	wh3_main_effect_corruption_chaos_technology	faction_to_province_own	0.0000
wh2_main_tech_def_3_3_2_slaanesh	wh3_main_effect_corruption_chaos_technology	faction_to_province_own	0.0000

to this fix and 

wh2_main_anc_weapon_heartrender_and_the_darksword	wh3_main_effect_corruption_chaos_characters	character_to_province_any	0.0000

to the weapon fix.

**Comment by Gingerglaahk** [comment]
@floskan so I should have both wh3_main_effect_corruption_slaanesh_technology lines and wh3_main_effect_corruption_chaos_technology but the chaos one should have 0 effect?

**Comment by Gingerglaahk** [comment]
Thanks! 
Edited them both

**Comment by floskan** [comment]
> Thanks! Edited them both

Nice!

Also, i looked around in the tables and morathi uses wh3_main_effect_corruption_slaanesh_characters_no_tr for her lord trait, might be better to change wh3_main_effect_corruption_slaanesh_characters to that effect instead on the fix for her weapon!

**Comment by Gingerglaahk** [comment]
> Also, i looked around in the tables and morathi uses wh3_main_effect_corruption_slaanesh_characters_no_tr for her lord trait, might be better to change wh3_main_effect_corruption_slaanesh_characters to that effect instead on the fix for her weapon!

Why is that a fix for the weapon?

It seems that wh3_main_effect_corruption_slaanesh_characters_no_tr can indeed be replaced by wh3_main_effect_corruption_slaanesh_characters (because I couldn't find anywhere else with the no_tr mentioned and it is maybe a remnant of something older, maybe from WH2).
Everything else about Morathi's corruption is working ok (that's how I noticed it).

**Comment by floskan** [comment]
> > Also, i looked around in the tables and morathi uses wh3_main_effect_corruption_slaanesh_characters_no_tr for her lord trait, might be better to change wh3_main_effect_corruption_slaanesh_characters to that effect instead on the fix for her weapon!
> 
> Why is that a fix for the weapon?
> 
> It seems that wh3_main_effect_corruption_slaanesh_characters_no_tr can indeed be replaced by wh3_main_effect_corruption_slaanesh_characters (because I couldn't find anywhere else with the no_tr mentioned and it is maybe a remnant of something older, maybe from WH2). Everything else about Morathi's corruption is working ok (that's how I noticed it).

Yeah her trait works fine, i meant changing the line in your weapon fix from wh3_main_effect_corruption_slaanesh_characters to wh3_main_effect_corruption_slaanesh_characters_no_tr for consistency's sake since she already makes use of that effect. Seems to be used by Sigvald and her.

**Comment by Gingerglaahk** [comment]
Done!

**Comment by floskan** [comment]
> Done!

Perfect 👍

**Comment by mfvreeland** [comment]
@Gingerglaahk or @floskan have these changes been tested?

**Comment by floskan** [comment]
> @Gingerglaahk or @floskan have these changes been tested?

Yeah, it works.

**Comment by Gingerglaahk** [comment]
> This doesn't remove the undivided corruption, you should add
> 
> wh2_main_tech_def_1_3_3_slaanesh wh3_main_effect_corruption_chaos_technology faction_to_province_own 0.0000 wh2_main_tech_def_3_3_2_slaanesh wh3_main_effect_corruption_chaos_technology faction_to_province_own 0.0000
> 
> to this fix and
> 
> wh2_main_anc_weapon_heartrender_and_the_darksword wh3_main_effect_corruption_chaos_characters character_to_province_any 0.0000
> 
> to the weapon fix.

Now it shows this: (Chaos Undivided Corruption +0)

image
image

@floskan So maybe we shouldn't have added those lines? 🤔 Or no way around it?
Should I open another PR to fix this?

**Comment by floskan** [comment]
> > This doesn't remove the undivided corruption, you should add
> > wh2_main_tech_def_1_3_3_slaanesh wh3_main_effect_corruption_chaos_technology faction_to_province_own 0.0000 wh2_main_tech_def_3_3_2_slaanesh wh3_main_effect_corruption_chaos_technology faction_to_province_own 0.0000
> > to this fix and
> > wh2_main_anc_weapon_heartrender_and_the_darksword wh3_main_effect_corruption_chaos_characters character_to_province_any 0.0000
> > to the weapon fix.
> 
> Now it shows this: (Chaos Undivided Corruption +0)
> 
> image image
> 
> @floskan So maybe we shouldn't have added those lines? 🤔 Or no way around it? Should I open another PR to fix this?

You should have, otherwise it would be +5 to both corruption types. It's the easiest way to deal with these kinds of bugs and it doesn't ruin compability with other mods.

**Comment by mfvreeland** [comment]
@floskan is right that the old effect needed to be changed, and that's the most important thing. You should be able to get rid of the tooltip for the old effect by changing its scope to `faction_to_province_own_unseen`, though. We can update that for the next version. The good thing is that it's just a visual thing, gameplay-wise the problem has been fixed already.

**Comment by floskan** [comment]
Oh yeah, i missed that. My bad.

**Comment by pigwithsnoot** [comment]
These were all fixed today by CA in patch 2.2.

**Comment by Gingerglaahk** [comment]
All my precious Morathi fixes :smiling_face_with_tear:

**Comment by Gingerglaahk** [comment]
@mfvreeland Do you want me to open a PR that reverts all of them or are you going to do that?

**Comment by mfvreeland** [comment]
@Gingerglaahk I'm not sure we need to go through the whole PR process just to revert some changes. I'll go through and revert things confirmed fixed by CA as soon as I get a chance.

**Pull request merged**
