### PR TITLE
Fix for #637

### PR DESCRIPTION
**Pull request by Pterosquirrel**
Adds a single missed table entry to building chain unlocks so Skaven get 10 building slots in Karak Eight Peaks (matching Greenskins/Dwarves as of 2.3)

### CODE REVIEW

**Comment by Pterosquirrel** [comment]
#637

**Comment by Harmandodelavega** [comment]
Did you test this? @Pterosquirrel

**Comment by Pterosquirrel** [comment]
Yep tested in both new and ongoing campaigns and K8P behaves as a normal 10-slot (2/4/6/8/9) as Skaven. No effect for other factions.

**Comment by Harmandodelavega** [comment]
Sorry man gonna need a .tsv file before I pull

**Comment by Pterosquirrel** [comment]
Whoops, exported it wrong... this should be it.

**Pull request merged**
