### PR TITLE
Fix for issue #1409 , trophy effect bundle level

### PR DESCRIPTION
**Pull request by floskan**
Fix by Drazhir

### CODE REVIEW

**Comment by mfvreeland** [comment]
You're missing a function close on this (one more "end" at the end).

**Comment by floskan** [comment]
This works then?

**Comment by Drazhir2** [comment]
It's still wrong, you were missing more than a **end** statement, you also removed 3 lines of script before that **end**.

**Comment by floskan** [comment]
This is now mergeable, my bad

**Pull request merged**
