### PR TITLE
Fix for #1163

### LINKED ISSUE #1163: Thorek and Runelords use the wrong animations (+Awsomnerd/Mandras)
#867
Thorek Ironbrow and Runelords use Thorgrims unarmed anvil animations, instead of their own uniqe ones given to them in game 2. Some of their vfx are missing as well.
 
I have already made a mod that fixes these issues called Thorek Animation and Floating Anvil Fix here, https://steamcommunity.com/sharedfiles/filedetails/?id=2945364561

Play as Runelords or Thorek in wh2 to notice they had animations where they strike their anvils and lighting spreads across the ground for all their attacks and charges. Then play game 3 and you'll see they are using Thorgrims anvil animation instead, as well as vfx missing from their hammers.

They are really cool animations and deserve to be in the game I've reported it everwhere I could report, but it has yet to be acknowledged by CA so far.

### PR DESCRIPTION
**Pull request by mfvreeland**
This incorporates Awsomnerd's fix from Steam workshop, but it also preserves the spellcasting animations and removes some unnecessary db changes. Additionally, the old sound metadata and jumping attack animation have been restored (this was not done in the original mod).

Fixes #1163

### CODE REVIEW

**Comment by floskan** [comment]
> This incorporates Awsomnerd's fix from Steam workshop, but it also preserves the spellcasting animations and removes some unnecessary db changes. Additionally, the old sound metadata and jumping attack animation have been restored (this was not done in the original mod).
> 
> Fixes #1163

@mfvreeland I did some testing! Everything seems to be working. No casting animation for either runelord or Thorek on foot but it's like that in vanilla too. Don't have Wh2 installed currently so can't compare.

**Comment by mfvreeland** [comment]
> I downloaded it out of curiosity, they did have on foot casting animations as well.

It doesn't look like those animations exist in WH3 by default, but we could probably re-add them. Unfortunately, I don't have WH2 installed anymore. If you can export `animations\battle\humanoid03` (all folders) and `animations\database\battle\bin\hu3_runelord_hammer.bin` and share these in .ZIP or something, I can probably restore this as well. Alternatively, we could use the casting animations from the Chaos Dwarfs as they share the same skeleton, but this might look a little like Thorek has been possessed.

**Comment by floskan** [comment]
> > I downloaded it out of curiosity, they did have on foot casting animations as well.
> 
> It doesn't look like those animations exist in WH3 by default, but we could probably re-add them. Unfortunately, I don't have WH2 installed anymore. If you can export `animations\battle\humanoid03` (all folders) and `animations\database\battle\bin\hu3_runelord_hammer.bin` and share these in a .ZIP or something, I can probably restore this as well. Alternatively, we could use the casting animations from the Chaos Dwarfs as they share the same skeleton, but this might look a little like Thorek has been possessed.


[animrunelord.zip](https://github.com/chadvandy/cbfm_wh3/files/14440522/animrunelord.zip)

Would this work? The file structure is set up differently in game 2 it seems, there's nothing like hu3_runelord_hammer.bin you wanted me to export. Found a txt in animation_fragments named hu3_runelord_hammer and that's the closest thing i could find right now. Can take a closer look tomorrow if that won't work

**Comment by mfvreeland** [comment]
That should be enough to work with! I'll see what I can do.

**Comment by floskan** [comment]
Good job with this fix🥳

**Pull request merged**
